name: "FRC West Curriculum"
description: "FRC West's Robotics Curriculum"

url: http://www.frc-west.github.io

permalink: pretty
markdown: rdiscount

# Site Navigation
courses: 
-
    course: CSE 1010 - Computer Science 1
    base: /courses/CSE1010
    url: /courses/CSE1010/home
    groups:

    -
        group: Computer Science
    -
        group: Computation
    -
        group: Programming
    -
        group: Information Technology
    -
        group: Algorithms Data Structure

-
    course: CSE 1110 - Structured Programming 1
    base: /courses/CSE1110
    url: /courses/CSE1110/home
    desc: Computer Science course for introductory programming and control flow
    groups:

    -
        group: Programs
        units:
        -
            unit: Programming
            url: /courses/CSE1110/1-Programs/1-Programming 

        -
            unit: Languages
            url: /courses/CSE1110/1-Programs/2-Languages 

        -
            unit: Libraries
            url: /courses/CSE1110/1-Programs/3-Libraries 

        -
            unit: Binary
            url: /courses/CSE1110/1-Programs/4-Binary 

    -
        group: Data
        units:
        -
            unit: Data Types
            url: /courses/CSE1110/2-Data/1-DataTypes 

        -
            unit: Variables
            url: /courses/CSE1110/2-Data/2-Variables 

        -
            unit: Input and Output
            url: /courses/CSE1110/2-Data/3-InputandOutput 

    -
        group: Basic Calculations
        units:
        -
            unit: Intro to Basic Calculations
            url: /courses/CSE1110/3-BasicCalculations/1-Intro 

        -
            unit: Activity - Basic Calculations
            url: /courses/CSE1110/3-BasicCalculations/2-Activity 

    -
        group: Algorithms
        units:
        -
            unit: Control Flow
            url: /courses/CSE1110/4-Algorithms/1-ControlFlow 

        -
            unit: Functions
            url: /courses/CSE1110/4-Algorithms/2-Functions 

        -
            unit: Input and Output
            url: /courses/CSE1110/4-Algorithms/3-InputandOutput 

    -
        group: Calculator
        units:
        -
            unit: Intro to Calculator Activity
            url: /courses/CSE1110/5-Calculator/1-Intro 

        -
            unit: Calculator Activity
            url: /courses/CSE1110/5-Calculator/2-Activity 

    -
        group: Environment
        units:
        -
            unit: Running Programs
            url: /courses/CSE1110/6-Environment/1-RunningPrograms 

        -
            unit: Programming Tools
            url: /courses/CSE1110/6-Environment/2-ProgrammingTools 

        -
            unit: Debugging
            url: /courses/CSE1110/6-Environment/3-Debugging 

    -
        group: FRC
        units:
        -
            unit: FRC Programming
            url: /courses/CSE1110/7-FRC/1-FRCProgramming 


-
    course: CSE 1120 - Structured Programming 2
    base: /courses/CSE1120
    url: /courses/CSE1120/home
    desc: Computer Science course for programming systems
    groups:

    -
        group: Decisions
        units:
        -
            unit: Statements as Decisions
            url: /courses/CSE1120/1-Decisions/1-StatementsasDecisions 

        -
            unit: Edge Cases
            url: /courses/CSE1120/1-Decisions/2-EdgeCases 

        -
            unit: Accuracy
            url: /courses/CSE1120/1-Decisions/3-Accuracy 

        -
            unit: Consistency
            url: /courses/CSE1120/1-Decisions/4-Consistency 

    -
        group: Math Functions
        units:
        -
            unit: Introduction to Math Functions Activity
            url: /courses/CSE1120/2-MathFunctions/1-Intro 

        -
            unit: Math Functions Activity
            url: /courses/CSE1120/2-MathFunctions/2-Activity 

    -
        group: Repetition
        units:
        -
            unit: Looping
            url: /courses/CSE1120/3-Repetition/1-Looping 

        -
            unit: Iteration
            url: /courses/CSE1120/3-Repetition/2-Iteration 

        -
            unit: Repetition as a Problem Solver
            url: /courses/CSE1120/3-Repetition/3-RepetitionasaProblemSolver 

    -
        group: IPO
        units:
        -
            unit: Parsing
            url: /courses/CSE1120/4-IPO/1-Parsing 

        -
            unit: Processing
            url: /courses/CSE1120/4-IPO/2-Processing 

        -
            unit: Output
            url: /courses/CSE1120/4-IPO/3-Output 

    -
        group: Debugging
        units:
        -
            unit: Errors
            url: /courses/CSE1120/5-Debugging/1-Errors 

        -
            unit: Syntax
            url: /courses/CSE1120/5-Debugging/2-Syntax 

    -
        group: Primes
        units:
        -
            unit: Intro to Primes Activity
            url: /courses/CSE1120/6-Primes/1-Intro 

        -
            unit: Prime Numbers Activity
            url: /courses/CSE1120/6-Primes/2-Activity 


-
    course: CSE 1240 - Robotics Programming 1
    base: /courses/CSE1240
    url: /courses/CSE1240/home
    groups:

    -
        group: Robotics
    -
        group: Embedded Systems
    -
        group: Robotic Control
    -
        group: Environment
    -
        group: Input Output Programming Methodology

-
    course: ELT 1010 - Electro-Assembly 1
    base: /courses/ELT1010
    url: /courses/ELT1010/home
    desc: Electronics course for introductory skills and knowledge
    groups:

    -
        group: Safety
        units:
        -
            unit: Workplace Management
            url: /courses/ELT1010/1-Safety/1-WorkplaceManagement 

        -
            unit: Safe Work Practices
            url: /courses/ELT1010/1-Safety/2-SafeWorkPractices 

        -
            unit: Hazard Identification and Control
            url: /courses/ELT1010/1-Safety/3-HazardIdentificationandControl 

        -
            unit: Mini Animation Activity
            url: /courses/ELT1010/1-Safety/4-Activity 

    -
        group: Electronics
        units:
        -
            unit: Circuits
            url: /courses/ELT1010/2-Electronics/1-Circuits 

        -
            unit: Electrical Components
            url: /courses/ELT1010/2-Electronics/2-ElectricalComponents 

        -
            unit: Electronic Devices
            url: /courses/ELT1010/2-Electronics/3-ElectronicDevices 

        -
            unit: Electronic Connections
            url: /courses/ELT1010/2-Electronics/4-ElectronicConnections 

    -
        group: Sensors
        units:
        -
            unit: Activity - Sensors
            url: /courses/ELT1010/3-Sensors/1-Activity 

    -
        group: Fabricationof Components
        units:
        -
            unit: Soldering
            url: /courses/ELT1010/4-FabricationofComponents/1-Soldering 

        -
            unit: Application of Electronic Components
            url: /courses/ELT1010/4-FabricationofComponents/2-ApplicationofElectronicComponents 

        -
            unit: Analog Connections
            url: /courses/ELT1010/4-FabricationofComponents/3-AnalogConnections 

        -
            unit: Digital Connections
            url: /courses/ELT1010/4-FabricationofComponents/4-DigitalConnections 

    -
        group: Soldering
        units:
        -
            unit: Activity - Soldering
            url: /courses/ELT1010/5-Soldering/1-Activity 

    -
        group: FRC
        units:
        -
            unit: FRC Electronics
            url: /courses/ELT1010/6-FRC/1-FRCElectronics 


-
    course: ELT 1080 - Control Systems 1
    base: /courses/ELT1080
    url: /courses/ELT1080/home
    desc: Control systems course for learning the basics of control theory
    groups:

    -
        group: Control System
        units:
        -
            unit: Circuits
            url: /courses/ELT1080/1-ControlSystem/1-Circuits 

        -
            unit: Loops
            url: /courses/ELT1080/1-ControlSystem/2-Loops 

        -
            unit: Ground
            url: /courses/ELT1080/1-ControlSystem/3-Ground 

        -
            unit: Control
            url: /courses/ELT1080/1-ControlSystem/4-Control 

        -
            unit: Input to Output
            url: /courses/ELT1080/1-ControlSystem/5-InputtoOutput 

    -
        group: Devices
        units:
        -
            unit: Sensors
            url: /courses/ELT1080/2-Devices/1-Sensors 

        -
            unit: Processors
            url: /courses/ELT1080/2-Devices/2-Processors 

        -
            unit: Actuators
            url: /courses/ELT1080/2-Devices/3-Actuators 

        -
            unit: Control
            url: /courses/ELT1080/2-Devices/4-Control 

        -
            unit: Measurement
            url: /courses/ELT1080/2-Devices/5-Measurement 

    -
        group: Testing
        units:
        -
            unit: Measuring
            url: /courses/ELT1080/3-Testing/1-Measuring 

        -
            unit: Testing / Measuring Activity
            url: /courses/ELT1080/3-Testing/2-Activity 


-
    course: ELT 1130 - Robotics 1
    base: /courses/ELT1130
    url: /courses/ELT1130/home
    desc: Robotics course for introduction to robotics and its applications
    groups:

    -
        group: Robots
        units:
        -
            unit: Principles of Robotics
            url: /courses/ELT1130/1-Robots/1-Principles 

        -
            unit: Control
            url: /courses/ELT1130/1-Robots/2-Control 

        -
            unit: Design
            url: /courses/ELT1130/1-Robots/3-Design 

        -
            unit: Usage
            url: /courses/ELT1130/1-Robots/4-Usage 

    -
        group: Subsystems
        units:
        -
            unit: Motors
            url: /courses/ELT1130/2-Subsystems/1-Motors 

        -
            unit: Pneumatics
            url: /courses/ELT1130/2-Subsystems/2-Pneumatics 

        -
            unit: Electronics
            url: /courses/ELT1130/2-Subsystems/3-Electronics 

        -
            unit: Drivetrains
            url: /courses/ELT1130/2-Subsystems/4-Drivetrains 

    -
        group: Power Sources
        units:
        -
            unit: Electricity
            url: /courses/ELT1130/3-PowerSources/1-Electricity 

        -
            unit: Pneumatic and Hydraulic
            url: /courses/ELT1130/3-PowerSources/2-Pneumatic&Hydraulic 

    -
        group: Vex Robot
        units:
        -
            unit: Vex Robot Activity
            url: /courses/ELT1130/4-VexRobot/1-Activity 

    -
        group: FRC
        units:
        -
            unit: FRC
            url: /courses/ELT1130/5-FRC/1-FRC 


-
    course: ELT 1140 - Robotics Applications
    base: /courses/ELT1140
    url: /courses/ELT1140/home
    desc: Second level robotics course for more robotics and its applications
    groups:

    -
        group: Robots
        units:
        -
            unit: History
            url: /courses/ELT1140/1-Robots/1-History 

        -
            unit: Industry
            url: /courses/ELT1140/1-Robots/2-Industry 

        -
            unit: Power Sources
            url: /courses/ELT1140/1-Robots/3-PowerSources 

    -
        group: Programming
        units:
        -
            unit: Motor Control
            url: /courses/ELT1140/2-Programming/1-MotorControl 

        -
            unit: Downloading
            url: /courses/ELT1140/2-Programming/2-Downloading 

    -
        group: Robotic System
        units:
        -
            unit: Robotic System Activity
            url: /courses/ELT1140/3-RoboticSystem/1-Activity 


-
    course: ELT 1910 - ELT Project A
    base: /courses/ELT1910
    url: /courses/ELT1910/home
    desc: CTS Project for FRC team members
    groups:

    -
        group: FRC
        units:
        -
            unit: FRC
            url: /courses/ELT1910/1-FRC/1-FRC 

    -
        group: Kitbot
        units:
        -
            unit: Kitbot
            url: /courses/ELT1910/2-Kitbot/1-Activity 

    -
        group: Build Season
        units:
        -
            unit: Build Season
            url: /courses/ELT1910/3-BuildSeason/1-Activity 


-
    course: ELT 2080 - Control Systems 2
    base: /courses/ELT2080
    url: /courses/ELT2080/home
    groups:

    -
        group: Power
    -
        group: Semiconductors
    -
        group: Sensors
    -
        group: Project

-
    course: ELT 2130 - Magnetic Control Devices
    base: /courses/ELT2130
    url: /courses/ELT2130/home
    groups:

    -
        group: Electromagnetism
    -
        group: Relays Switches
    -
        group: Circuits
    -
        group: Project
    -
        group: Control Devices

-
    course: ELT 2140 - Robotics 2
    base: /courses/ELT2140
    url: /courses/ELT2140/home
    groups:

    -
        group: Sensor Devices
    -
        group: Control Systems
    -
        group: Utilizing Input
    -
        group: Project

-
    course: ELT 2180 - Process Control
    base: /courses/ELT2180
    url: /courses/ELT2180/home
    groups:

    -
        group: Simulation
    -
        group: Movement Control
    -
        group: Processes
    -
        group: Project

-
    course: ELT 2910 - ELT Project B
    base: /courses/ELT2910
    url: /courses/ELT2910/home
    groups:

    -
        group: FRC
    -
        group: Build Season
    -
        group: Design Writeup

-
    course: Special Projects
    base: /courses/SpecialProjects
    url: /courses/SpecialProjects/home
    desc: Project credits for build season hours (FRC)
    groups:

    -
        group: Proposal
        units:
        -
            unit: FRC Team Member Special Projects Proposal
            url: /courses/SpecialProjects/1-Proposal/1-Proposal 


